# Generated by Django 5.2.6 on 2025-09-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('hoursAvailable', models.IntegerField()),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('rooms', models.ManyToManyField(blank=True, to='roombook.classrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Roombook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='roombook.classrooms')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roombook.students')),
            ],
        ),
    ]
