# Generated by Django 5.2.6 on 2025-09-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='hoursAvailable',
            new_name='hours_Available',
        ),
    ]
