# Generated by Django 5.2.6 on 2025-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0002_rename_hoursavailable_classrooms_hours_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='students',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='students', to='roombook.classrooms'),
        ),
    ]
