# Generated by Django 5.2.6 on 2025-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0003_remove_classrooms_is_available_alter_students_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
