# Generated by Django 5.2.6 on 2025-09-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0004_classrooms_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roombook',
        ),
    ]
