# Generated by Django 5.2.6 on 2025-09-13 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0006_remove_classrooms_hours_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_active_slot_per_room',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('canceled', False)), fields=('classroom', 'date', 'start_time'), name='uniq_room_slot_active'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('canceled', False)), fields=('user', 'classroom', 'date'), name='one_hour_per_room_per_day'),
        ),
    ]
