# Generated by Django 5.2.6 on 2025-09-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0007_remove_booking_uniq_active_slot_per_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='uniq_room_slot_active',
        ),
    ]
