# Generated by Django 5.2.6 on 2025-09-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0008_remove_booking_uniq_room_slot_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrooms',
            options={'verbose_name_plural': 'Classrooms'},
        ),
    ]
